spring.application.name=Supermercado
# Configuração do Banco de Dados H2
spring.datasource.url=jdbc:h2:file:./dados_supermercado
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar o painel no navegador para poder ver as tabelas (localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# O Spring vai criar as tabelas automaticamente baseado na classe Produto
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true